# Generated by Django 3.2.2 on 2021-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='or_amount',
            field=models.IntegerField(default=0),
        ),
    ]
