# Generated by Django 3.2.2 on 2021-12-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211124_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_password', models.CharField(max_length=25)),
                ('user_phone', models.CharField(max_length=25)),
            ],
        ),
    ]
